---
    - name: configure domain name
      ios_system:
        domain_name: test.local
   
    - name: configure name servers
      ios_system:
        name_servers:
          - 8.8.8.8
          - 114.114.114.114

    - name: save configuation
      ios_config:
        save_when: modified       
...
